### ISSUE TITLE
can not run it

### ISSUE THREAD

**Issue by daniel4git** [Deali-Axy/CrazyAlpha#1]
thx for the great project, and i wanna try it 

when i run it with the jar file i got this message:
Error: Could not find or load main class game.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

when i run it in idea  i got this:
/soft/sss/openjdk11/bin/java -Djava.library.path=/soft/sss/javafx-sdk-11.0.1/lib --add-modules javafx.base,javafx.graphics --add-reads javafx.base=ALL-UNNAMED --add-reads javafx.graphics=ALL-UNNAMED -javaagent:/soft/sss/ideaIU/lib/idea_rt.jar=38465:/soft/sss/ideaIU/bin -Dfile.encoding=UTF-8 -classpath /soft/projects/IdeaProjects/CrazyAlpha/out/production/classes:/home/cyy/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/26.0-jre/6a806eff209f36f635f943e16d97491f00f6bfab/guava-26.0-jre.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.11.1/592a48674c926b01a9a747c7831bcd82a9e6d6e4/log4j-core-2.11.1.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.frice/engine/1.8.5/c07ec86ed1fbcd24d794f2521a0b6ea9bc6d9128/engine-1.8.5.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/com.googlecode.soundlibs/jlayer/1.0.1.4/b8df07ad72b482f7d6e6dee7fed669385e8dd92f/jlayer-1.0.1.4.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/com.github.jengelman.gradle.plugins/shadow/4.0.3/e250534a61a6e1ba60a835574553165ff6617cd3/shadow-4.0.3.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.2/25ea2e8b0c338a877313bd4672d3fe056ea78f0d/jsr305-3.0.2.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.checkerframework/checker-qual/2.5.2/cea74543d5904a30861a61b4643a5f2bb372efc4/checker-qual-2.5.2.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.1.3/39b109f2cd352b2d71b52a3b5a1a9850e1dc304b/error_prone_annotations-2.1.3.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/1.1/976d8d30bebc251db406f2bdb3eb01962b5685b3/j2objc-annotations-1.1.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.codehaus.mojo/animal-sniffer-annotations/1.14/775b7e22fb10026eed3f86e8dc556dfafe35f2d5/animal-sniffer-annotations-1.14.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.11.1/268f0fe4df3eefe052b57c87ec48517d64fb2a10/log4j-api-2.11.1.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.2.41/5e34ca185bbea7452d704ed3537a22314a809383/kotlin-stdlib-jdk8-1.2.41.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/junit/junit/3.8.2/7e4cde26b53a9a0e3fe5b00d1dbbc7cc1d46060/junit-3.8.2.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.2.41/d0cfb3ef897c00449e5e696355db9506225fb507/kotlin-stdlib-jdk7-1.2.41.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.41/7e34f009642702250bccd9e5255866f408962a05/kotlin-stdlib-1.2.41.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar:/home/cyy/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-backports-compat23/2.4.15/96cbcd01eaa6038f900b7154d08aae462c5430e/groovy-backports-compat23-2.4.15.jar:/soft/sss/javafx-sdk-11.0.1/lib/src.zip:/soft/sss/javafx-sdk-11.0.1/lib/javafx-swt.jar:/soft/sss/javafx-sdk-11.0.1/lib/javafx.web.jar:/soft/sss/javafx-sdk-11.0.1/lib/javafx.base.jar:/soft/sss/javafx-sdk-11.0.1/lib/javafx.fxml.jar:/soft/sss/javafx-sdk-11.0.1/lib/javafx.media.jar:/soft/sss/javafx-sdk-11.0.1/lib/javafx.swing.jar:/soft/sss/javafx-sdk-11.0.1/lib/jfoenix-9.0.8.jar:/soft/sss/javafx-sdk-11.0.1/lib/javafx.controls.jar:/soft/sss/javafx-sdk-11.0.1/lib/javafx.graphics.jar:/soft/sss/javafx-sdk-11.0.1/lib/controlsfx-9.0.0.jar:/soft/sss/javafx-sdk-11.0.1/lib/controlsfx-9.0.0.zip:/soft/sss/javafx-sdk-11.0.1/lib/fxsampler-1.0.10.jar:/soft/sss/javafx-sdk-11.0.1/lib/controlsfx-samples-9.0.0.jar -p /soft/sss/javafx-sdk-11.0.1/lib/javafx.base.jar:/soft/sss/javafx-sdk-11.0.1/lib/javafx.graphics.jar game.Main
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
08:13:42.639 [JavaFX Application Thread] ERROR game.Manager.ResouceManager - fonts resources is not exist!
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:418)
	at game.Manager.ResouceManager.loadResourcesFromOuter(ResouceManager.java:105)
	at game.Manager.ResouceManager.loadResources(ResouceManager.java:62)
	at game.Manager.ResouceManager.<init>(ResouceManager.java:52)
	at game.Game.<init>(Game.java:29)
	at game.Game.getInstance(Game.java:63)
	at game.Main.start(Main.java:22)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
Exception running application game.Main

Process finished with exit code 1

**Comment by Deali-Axy** [comment]
So sorry that so late to reply.
there is no javafx support in jdk11, neither oracle jdk or openjdk.

so you should run it on jdk8.
